from __future__ import annotations

import json
import re
from typing import Any

from backend.core.config import get_settings
from backend.models import GeneratedSQL


SQL_SYSTEM_PROMPT = """
You generate DuckDB SQL for a secure enterprise parquet analytics system.
Raw parquet files, full tables, vector embeddings, and local database contents are never sent to you.
You receive only locally retrieved metadata snippets from Qdrant and must return one read-only SQL query.

Rules:
- Return JSON only, with no markdown.
- Use only the relation_name values listed in allowed_relations.
- Use exact column names from relevant_columns and quote identifiers with double quotes.
- Generate only SELECT or WITH queries.
- Never use read_parquet, parquet_scan, file paths, URLs, COPY, INSTALL, LOAD, CREATE, INSERT, UPDATE, DELETE, DROP, ALTER, PRAGMA, ATTACH, or external scans.
- Include a LIMIT unless the query returns a single aggregate row.
- Prefer DuckDB-compatible SQL.
- If the question is ambiguous, use the highest scoring relevant columns and explain the assumption.
""".strip()


ANSWER_SYSTEM_PROMPT = """
You write concise analytics answers for enterprise users.
Use only the supplied SQL result preview and metadata. Do not invent rows, files, or values.
Mention uncertainty when the result preview is empty or incomplete. Keep the answer short and decision-ready.
""".strip()


class AnthropicRAGClient:
    def __init__(self) -> None:
        self.settings = get_settings()
        self._client = None

    @property
    def available(self) -> bool:
        return bool(self.settings.anthropic_enabled and self.settings.anthropic_api_key)

    @property
    def client(self):
        if self._client is None:
            from anthropic import Anthropic

            self._client = Anthropic(
                api_key=self.settings.anthropic_api_key,
                timeout=self.settings.anthropic_timeout_seconds,
            )
        return self._client

    def base_usage(self) -> dict[str, Any]:
        return {
            "provider": "anthropic",
            "model": self.settings.anthropic_model,
            "enabled": self.available,
            "configured": bool(self.settings.anthropic_api_key),
        }

    def generate_sql(
        self,
        *,
        question: str,
        rag_context: dict[str, Any],
        previous_sql: str | None = None,
        previous_error: str | None = None,
        attempt: int = 0,
    ) -> tuple[GeneratedSQL, dict[str, Any]]:
        if not self.available:
            raise RuntimeError("Anthropic is not configured. Set ANTHROPIC_API_KEY in .env.")

        user_payload = {
            "task": "Generate a safe DuckDB SQL query for the user question.",
            "question": question,
            "rag_context": rag_context,
            "previous_sql": previous_sql,
            "previous_error": previous_error,
            "json_schema": {
                "sql": "string, SELECT/WITH only",
                "intent": "short snake_case label",
                "aggregation": "aggregation name or null",
                "metric_column": "column name or table.column label or null",
                "group_by_columns": ["column names or labels"],
                "selected_columns": ["column names or labels"],
                "explanation": "brief reason for the query",
            },
        }
        text, usage = self._message(
            system=SQL_SYSTEM_PROMPT,
            payload=user_payload,
            max_tokens=self.settings.anthropic_max_tokens_sql,
        )
        parsed = self._parse_json_object(text)
        sql = str(parsed.get("sql", "")).strip()
        if not sql:
            raise ValueError("Claude did not return SQL.")

        return (
            GeneratedSQL(
                sql=sql,
                intent=str(parsed.get("intent") or "anthropic_sql"),
                aggregation=parsed.get("aggregation"),
                metric_column=parsed.get("metric_column"),
                group_by_columns=_as_string_list(parsed.get("group_by_columns")),
                selected_columns=_as_string_list(parsed.get("selected_columns")),
                limit=int(rag_context.get("requested_limit") or 100),
                explanation=str(parsed.get("explanation") or "Generated by Claude from minimal retrieved metadata."),
                source="anthropic_claude",
                validated=False,
                retry_count=attempt,
            ),
            usage,
        )

    def summarize_answer(
        self,
        *,
        question: str,
        result_context: dict[str, Any],
    ) -> tuple[str, dict[str, Any]]:
        if not self.available:
            raise RuntimeError("Anthropic is not configured. Set ANTHROPIC_API_KEY in .env.")

        user_payload = {
            "task": "Explain the local DuckDB query result in natural language.",
            "question": question,
            "result_context": result_context,
            "json_schema": {
                "answer": "short natural language answer grounded only in rows_preview",
            },
        }
        text, usage = self._message(
            system=ANSWER_SYSTEM_PROMPT,
            payload=user_payload,
            max_tokens=self.settings.anthropic_max_tokens_answer,
        )
        try:
            parsed = self._parse_json_object(text)
            answer = str(parsed.get("answer") or "").strip()
            if answer:
                return answer, usage
        except ValueError:
            pass
        return text.strip(), usage

    def _message(self, *, system: str, payload: dict[str, Any], max_tokens: int) -> tuple[str, dict[str, Any]]:
        message = self.client.messages.create(
            model=self.settings.anthropic_model,
            max_tokens=max_tokens,
            temperature=0,
            system=system,
            messages=[
                {
                    "role": "user",
                    "content": json.dumps(payload, ensure_ascii=False, default=str),
                }
            ],
        )
        return self._extract_text(message), self._usage(message)

    def _extract_text(self, message: Any) -> str:
        parts: list[str] = []
        for block in getattr(message, "content", []) or []:
            if isinstance(block, dict):
                if block.get("type") == "text":
                    parts.append(str(block.get("text", "")))
                continue
            if getattr(block, "type", None) == "text":
                parts.append(str(getattr(block, "text", "")))
        return "\n".join(part for part in parts if part).strip()

    def _usage(self, message: Any) -> dict[str, Any]:
        usage = getattr(message, "usage", None)
        return {
            "request_id": getattr(message, "_request_id", None),
            "input_tokens": getattr(usage, "input_tokens", None),
            "output_tokens": getattr(usage, "output_tokens", None),
        }

    def _parse_json_object(self, text: str) -> dict[str, Any]:
        cleaned = text.strip()
        fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", cleaned, flags=re.DOTALL)
        if fenced:
            cleaned = fenced.group(1)
        elif not cleaned.startswith("{"):
            start = cleaned.find("{")
            end = cleaned.rfind("}")
            if start >= 0 and end > start:
                cleaned = cleaned[start : end + 1]
        try:
            parsed = json.loads(cleaned)
        except json.JSONDecodeError as exc:
            raise ValueError(f"Claude returned non-JSON content: {text[:300]}") from exc
        if not isinstance(parsed, dict):
            raise ValueError("Claude JSON response must be an object.")
        return parsed


def _as_string_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value if item is not None]
    return [str(value)]
